title: "Benoît Rongeard"
description: "Tech lead — Freelance"
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme

# Site author / contact
author:
	name: "Benoît Rongeard"
	# email: you@example.com

social:
	linkedin: "https://linkedin.com/in/benoit-rongeard-678258100"

github: "https://github.com/benoitrongeard"
